### ISSUE TITLE
Error handling and retries on frisp read

### ISSUE THREAD

**Issue by stojg** [silverstripe-platform/frisp#5]
I've noticed in some occasions that read doesn't work. Here is an output

```
[+] frisp write 'password':'secret' to vault 'frisp-stack-test'
[+] frisp read password

Notice: Can't cache private key in /Users/slindqvist/Sites/frisp/Frisp/Reader.php on line 23

Fatal error: Uncaught exception 'Exception' with message 'Process exited before completing request' in /Users/slindqvist/Sites/frisp/Frisp/Reader.php:63
Stack trace:
#0 /Users/slindqvist/Sites/frisp/frisp.php(184): SilverStripe\Platform\Frisp\Reader->read('password')
#1 {main}
  thrown in /Users/slindqvist/Sites/frisp/Frisp/Reader.php on line 63
[+] frisp write 'password':'secret2' to vault 'frisp-stack-test'
[+] frisp read password

Notice: Can't cache private key in /Users/slindqvist/Sites/frisp/Frisp/Reader.php on line 23

Fatal error: Uncaught exception 'Exception' with message 'Process exited before completing request' in /Users/slindqvist/Sites/frisp/Frisp/Reader.php:63
Stack trace:
#0 /Users/slindqvist/Sites/frisp/frisp.php(184): SilverStripe\Platform\Frisp\Reader->read('password')
#1 {main}
  thrown in /Users/slindqvist/Sites/frisp/Frisp/Reader.php on line 63
```

Not sure if this is a race condition due to the write followed by an immediate read

**Comment by hafriedlander** [comment]
"Process exited before completing request" indicates a problem in the lambda layer. Try and catch it with --debug, but we can also see the logs in cloudwatch if you get there fast enough to pick which execution it was.

**Comment by stojg** [comment]
I'm going to close this since I haven't been able to reproduce this in more practical test pace.
